//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivaWallet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public long Id { get; set; }
        public bool IsDeleted { get; set; }
        public long AttachementSetId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string FilePath { get; set; }
        public string Url { get; set; }
        public string Caption { get; set; }
        public string MimeType { get; set; }
        public string HtmlCode { get; set; }
        public int OrderNo { get; set; }
    
        public virtual AttachmentSet AttachmentSet { get; set; }
    }
}
