//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivaWallet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStat
    {
        public long Id { get; set; }
        public bool IsDeleted { get; set; }
        public long ProjectId { get; set; }
        public long BackersNo { get; set; }
        public decimal MoneyPledged { get; set; }
        public int SharesNo { get; set; }
        public int CommentsNo { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
