//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivaWallet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.FundingPackages = new HashSet<FundingPackage>();
            this.ProjectComments = new HashSet<ProjectComment>();
            this.ProjectExternalShares = new HashSet<ProjectExternalShare>();
            this.ProjectStats = new HashSet<ProjectStat>();
            this.ProjectUpdates = new HashSet<ProjectUpdate>();
        }
    
        public long Id { get; set; }
        public bool IsDeleted { get; set; }
        public long UserId { get; set; }
        public long ProjectCategoryId { get; set; }
        public Nullable<long> AttachmentSetId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime FundingEndDate { get; set; }
        public decimal FundingGoal { get; set; }
        public string Status { get; set; }
    
        public virtual AttachmentSet AttachmentSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundingPackage> FundingPackages { get; set; }
        public virtual ProjectCategory ProjectCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectComment> ProjectComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectExternalShare> ProjectExternalShares { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStat> ProjectStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectUpdate> ProjectUpdates { get; set; }
    }
}
