//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivaWallet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ProjectComments = new HashSet<ProjectComment>();
            this.ProjectExternalShares = new HashSet<ProjectExternalShare>();
            this.Projects = new HashSet<Project>();
            this.UserFundings = new HashSet<UserFunding>();
        }
    
        public long Id { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public bool IsVerified { get; set; }
        public string VerificationToken { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string Name { get; set; }
        public string ShortBio { get; set; }
        public string AvatarImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectComment> ProjectComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectExternalShare> ProjectExternalShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFunding> UserFundings { get; set; }
    }
}
